package shell

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reshell/pkg/config"
	"strings"
)

const (
	StartMarker = "# >>> reshell initialize >>>"
	EndMarker   = "# <<< reshell initialize <<<"
)

// AsciiBanner contains the ASCII art warning block for shell profiles.
const AsciiBanner = `# +---------------------------------------------------------------+
# |                _ __ ___  ___| |__   ___| | |                  |
# |               | '__/ _ \/ __| '_ \ / _ \ | |                  |
# |               | | |  __/\__ \ | | |  __/ | |                  |
# |               |_|  \___||___/_| |_|\___|_|_|                  |
# |                                                               |
# |       WARNING: THIS BLOCK IS AUTOMATICALLY MANAGED BY RESHELL. |
# |       DO NOT MANUALLY UPDATE OR EDIT THE CODE WITHIN IT.      |
# +---------------------------------------------------------------+`

// DetectShell reads the SHELL environment variable to identify the active shell.
func DetectShell() string {
	shellEnv := os.Getenv("SHELL")
	if strings.Contains(shellEnv, "zsh") {
		return "zsh"
	}
	if strings.Contains(shellEnv, "fish") {
		return "fish"
	}
	return "bash" // default fallback
}

// GetShellProfile returns the absolute path of the current shell profile.
func GetShellProfile(shellName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	switch shellName {
	case "zsh":
		return filepath.Join(home, ".zshrc"), nil
	case "fish":
		return filepath.Join(home, ".config", "fish", "config.fish"), nil
	default:
		return filepath.Join(home, ".bashrc"), nil
	}
}

// Apply compiles configuration to reshell.sh/reshell.fish and updates the shell profile.
func Apply() error {
	shellName := DetectShell()

	// 1. Load configurations
	aliases, err := config.LoadAliases()
	if err != nil {
		return fmt.Errorf("failed to load aliases: %w", err)
	}

	envs, err := config.LoadEnv()
	if err != nil {
		return fmt.Errorf("failed to load env vars: %w", err)
	}

	configDir, err := config.GetConfigDir()
	if err != nil {
		return err
	}

	// 2. Generate script content based on the active shell
	var scriptBuilder strings.Builder
	scriptBuilder.WriteString("# Generated by reshell. Do not edit directly.\n\n")

	// Apply Env Vars
	scriptBuilder.WriteString("# --- Environment Variables ---\n")
	for _, env := range envs.Variables {
		if !env.Enabled {
			continue
		}
		if shellName == "fish" {
			scriptBuilder.WriteString(fmt.Sprintf("set -gx %s %q\n", env.Name, env.Value))
		} else {
			// bash & zsh
			scriptBuilder.WriteString(fmt.Sprintf("export %s=%q\n", env.Name, env.Value))
		}
	}
	scriptBuilder.WriteString("\n")

	// Apply Aliases
	scriptBuilder.WriteString("# --- Aliases ---\n")
	for _, alias := range aliases.Aliases {
		if !alias.Enabled {
			continue
		}
		// Check shell compatibility
		if alias.Shell != "all" && alias.Shell != shellName {
			continue
		}

		if shellName == "fish" {
			scriptBuilder.WriteString(fmt.Sprintf("alias %s %q\n", alias.Name, alias.Value))
		} else {
			scriptBuilder.WriteString(fmt.Sprintf("alias %s=%q\n", alias.Name, alias.Value))
		}
	}
	scriptBuilder.WriteString("\n")

	// Apply Functions
	scriptBuilder.WriteString("# --- Functions ---\n")
	funcDir, err := config.GetFunctionsDir()
	if err == nil {
		files, err := os.ReadDir(funcDir)
		if err == nil {
			for _, file := range files {
				if file.IsDir() {
					continue
				}
				ext := filepath.Ext(file.Name())
				name := strings.TrimSuffix(file.Name(), ext)
				fullPath := filepath.Join(funcDir, file.Name())

				if shellName == "fish" {
					if ext == ".fish" {
						scriptBuilder.WriteString(fmt.Sprintf("source %q\n", fullPath))
					} else if ext == ".sh" {
						// Create a fish function wrapper that runs the bash script
						scriptBuilder.WriteString(fmt.Sprintf("function %s\n    bash %q $argv\nend\n", name, fullPath))
					}
				} else {
					// bash / zsh
					if ext == ".sh" || ext == ".bash" || ext == "" {
						scriptBuilder.WriteString(fmt.Sprintf("source %q\n", fullPath))
					}
				}
			}
		}
	}

	// 3. Write compilation file
	var targetFile string
	if shellName == "fish" {
		targetFile = filepath.Join(configDir, "shell", "reshell.fish")
	} else {
		targetFile = filepath.Join(configDir, "shell", "reshell.sh")
	}

	err = os.WriteFile(targetFile, []byte(scriptBuilder.String()), 0644)
	if err != nil {
		return fmt.Errorf("failed to write compiled shell script: %w", err)
	}

	// 4. Update Shell Profile Startup Script
	profilePath, err := GetShellProfile(shellName)
	if err != nil {
		return err
	}

	// Ensure the profile directory exists (especially config.fish folder)
	profileDir := filepath.Dir(profilePath)
	if err := os.MkdirAll(profileDir, 0755); err != nil {
		return fmt.Errorf("failed to create profile directory: %w", err)
	}

	// Read existing content
	var profileContent string
	data, err := os.ReadFile(profilePath)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("failed to read shell profile: %w", err)
		}
	} else {
		profileContent = string(data)
	}

	// Construct reshell block to insert
	var loadCmd string
	if shellName == "fish" {
		loadCmd = fmt.Sprintf("if test -f %q\n    source %q\nend", targetFile, targetFile)
	} else {
		loadCmd = fmt.Sprintf("if [ -f %q ]; then\n    . %q\nfi", targetFile, targetFile)
	}

	newBlock := fmt.Sprintf("%s\n%s\n%s\n%s", AsciiBanner, StartMarker, loadCmd, EndMarker)

	var updatedContent string
	if strings.Contains(profileContent, StartMarker) && strings.Contains(profileContent, EndMarker) {
		// Replace the existing block
		startIndex := strings.Index(profileContent, StartMarker)
		// We want to find the start of the banner if it exists before StartMarker, or just StartMarker
		bannerIndex := strings.Index(profileContent, "# +---")
		replaceStart := startIndex
		if bannerIndex != -1 && bannerIndex < startIndex && strings.Contains(profileContent[bannerIndex:startIndex], "WARNING: THIS BLOCK") {
			replaceStart = bannerIndex
		}

		endIndex := strings.Index(profileContent, EndMarker) + len(EndMarker)
		updatedContent = profileContent[:replaceStart] + newBlock + profileContent[endIndex:]
	} else {
		// Append to the end
		if len(profileContent) > 0 && !strings.HasSuffix(profileContent, "\n") {
			profileContent += "\n"
		}
		updatedContent = profileContent + "\n" + newBlock + "\n"
	}

	err = os.WriteFile(profilePath, []byte(updatedContent), 0644)
	if err != nil {
		return fmt.Errorf("failed to update shell profile %q: %w", profilePath, err)
	}

	return nil
}

// Clean removes reshell block from shell profile startup script.
func Clean() error {
	shellName := DetectShell()
	profilePath, err := GetShellProfile(shellName)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(profilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	content := string(data)
	if !strings.Contains(content, StartMarker) || !strings.Contains(content, EndMarker) {
		return nil // nothing to clean
	}

	startIndex := strings.Index(content, StartMarker)
	bannerIndex := strings.Index(content, "# +---")
	replaceStart := startIndex
	if bannerIndex != -1 && bannerIndex < startIndex && strings.Contains(content[bannerIndex:startIndex], "WARNING: THIS BLOCK") {
		replaceStart = bannerIndex
	}

	endIndex := strings.Index(content, EndMarker) + len(EndMarker)
	updatedContent := content[:replaceStart] + content[endIndex:]

	// Clean up trailing empty lines
	updatedContent = strings.TrimRight(updatedContent, "\n") + "\n"
	if updatedContent == "\n" {
		updatedContent = ""
	}

	return os.WriteFile(profilePath, []byte(updatedContent), 0644)
}

// CopyFile helper copies a file from src to dst.
func CopyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	if err != nil {
		return err
	}
	return out.Sync()
}
