name: Go Tests and Build Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
      - name: Set up Go
        uses: actions/setup-go@3041de560034e262f551986c197b17f3698d274e # v5.2.0
        with:
          go-version: '1.22'
          cache: false
 
      - name: Verify Dependencies
        run: go mod verify
 
      - name: Build Binary
        run: go build -v ./...
 
      - name: Run Unit Tests with Coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd77a6f35a48282173593be2a9c3117578f780 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: false
